"""empty message

Revision ID: aa5220f6cfe1
Revises: f0461a9ff1ec
Create Date: 2020-07-25 08:01:49.521984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5220f6cfe1'
down_revision = 'f0461a9ff1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_teacher')
    # ### end Alembic commands ###
