"""empty message

Revision ID: c98218ef9be4
Revises: 151b88679058
Create Date: 2020-08-21 08:19:32.508020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98218ef9be4'
down_revision = '151b88679058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_structural', sa.Boolean(), nullable=True))
    op.alter_column('questions', 'b',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'b',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('questions', 'is_structural')
    # ### end Alembic commands ###
