"""empty message

Revision ID: ca5c6af86f70
Revises: aa5220f6cfe1
Create Date: 2020-07-27 14:14:51.309491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5c6af86f70'
down_revision = 'aa5220f6cfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('a', sa.String(length=128), nullable=False),
    sa.Column('b', sa.String(length=128), nullable=False),
    sa.Column('c', sa.String(length=128), nullable=True),
    sa.Column('d', sa.String(length=128), nullable=True),
    sa.Column('e', sa.String(length=128), nullable=True),
    sa.Column('correct', sa.String(length=1), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('courses')
    # ### end Alembic commands ###
